'use client';

import type { Metadata } from 'next';
import './globals.css';
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import { Providers } from './providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // 경로 변수 설정
  const basePath = process.env.NODE_ENV === 'production' ? '/yully' : '';

  return (
    <html lang="ko">
      <head>
        <style>{`
          :root {
            --base-path: "${basePath}";
          }
        `}</style>
      </head>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
