name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Create .env file
        run: |
          echo "NEXT_PUBLIC_APP_ENV_GMAIL_ADDRESS=${{ secrets.NEXT_PUBLIC_APP_ENV_GMAIL_ADDRESS }}" >> .env
          echo "NEXT_PUBLIC_APP_ENV_GMAIL_PASS=${{ secrets.NEXT_PUBLIC_APP_ENV_GMAIL_PASS }}" >> .env

      - name: Build
        run: npm run build

      - name: Add .nojekyll file
        run: touch ./out/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          cname: ollylove.co.kr
